name: deploy

run-name: 📋 @${{ github.triggering_actor }} is deploying

on:
    push:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - run: npm run build

      - name: package
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "out/" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git --exclude=.github \
            .

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v2
